version: "3.6"

services:
  app:
    image: revalle88/binance:latest
    build:
      context: .
    volumes:
      - ./src/binance:/app/src/binance
    env_file:
      - ./.env
    depends_on:
      - mongodb
      - rabbitmq
    command: celery -A binance.celery_app worker -l info -B
    restart: always
  rabbitmq:
      image: rabbitmq:3-management-alpine
      container_name: rabbitmq
  mongodb:
      image: mongo:latest
      hostname: mongodb
      environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
      volumes:
        - ./data/mongo:/data/db
      ports:
          - 27027:27017
      command: mongod --logpath=/dev/null # --quiet
#  tests:
#    image: tests
#    build:
#      context: .
#    volumes:
#      - ./src/binance:/app/src/binance
#    command: pytest reservation_invoices.tests