version: "3.6"

services:
  app:
    image: revalle88/binance:latest
    build:
      context: .
    volumes:
      - ./src/binance:/app/src/binance
    env_file:
      - ./.env
    depends_on:
      - redis
      - rabbitmq
    command: celery -A binance.celery_app worker -l info -B
    restart: always
  rabbitmq:
      image: rabbitmq:3-management-alpine
      container_name: rabbitmq
  redis:
    image: redis:alpine
    volumes:
      - ./state/postgres/data:/data
    ports:
      - 6399:6379
#  tests:
#    image: tests
#    build:
#      context: .
#    volumes:
#      - ./src/binance_worker:/app/src/binance_worker
#    command: pytest reservation_invoices.tests